using SwissTechTrainer.Domain.Enums;

namespace SwissTechTrainer.Domain.Entities;

/// <summary>
/// Represents a technical interview exercise within a specific category and difficulty level.
/// </summary>
public class Exercise
{
    private readonly List<Submission> _submissions = [];

    /// <summary>
    /// Gets the unique identifier for the exercise.
    /// </summary>
    public Guid Id { get; private set; }

    /// <summary>
    /// Gets the interview category this exercise belongs to.
    /// </summary>
    public CategoryType Category { get; private set; }

    /// <summary>
    /// Gets the difficulty level (1-5) of this exercise.
    /// </summary>
    public DifficultyLevel Level { get; private set; }

    /// <summary>
    /// Gets the descriptive title of the exercise.
    /// </summary>
    public string Title { get; private set; } = string.Empty;

    /// <summary>
    /// Gets the full problem description, scenario, and constraints.
    /// </summary>
    public string Description { get; private set; } = string.Empty;

    /// <summary>
    /// Gets the initial boilerplate or starter C# code provided to the candidate.
    /// </summary>
    public string StarterCode { get; private set; } = string.Empty;

    /// <summary>
    /// Gets the specification of the expected output format or deliverable.
    /// </summary>
    public string ExpectedOutputFormat { get; private set; } = string.Empty;

    /// <summary>
    /// Gets contextual hints displayed when the candidate unlocks Hint Mode.
    /// </summary>
    public string Hints { get; private set; } = string.Empty;

    /// <summary>
    /// Gets the optional reference identifier to a previous exercise used for negative prompting.
    /// </summary>
    public Guid? PreviousExerciseReferenceId { get; private set; }

    /// <summary>
    /// Gets a value indicating whether this exercise was dynamically synthesized by an LLM.
    /// </summary>
    public bool IsAIGenerated { get; private set; }

    /// <summary>
    /// Gets the UTC creation timestamp.
    /// </summary>
    public DateTime CreatedAt { get; private set; } = DateTime.UtcNow;

    /// <summary>
    /// Gets the read-only collection of candidate submissions recorded for this exercise.
    /// </summary>
    public IReadOnlyCollection<Submission> Submissions => _submissions.AsReadOnly();

    /// <summary>
    /// Parameterless constructor required by EF Core.
    /// </summary>
    private Exercise() { }

    /// <summary>
    /// Initializes a new instance of the <see cref="Exercise"/> entity.
    /// </summary>
    public Exercise(
        CategoryType category,
        DifficultyLevel level,
        string title,
        string description,
        string starterCode,
        string expectedOutputFormat = "C# Source File (.cs) or Architectural Justification",
        string hints = "",
        bool isAiGenerated = false,
        Guid? previousExerciseReferenceId = null)
    {
        Id = Guid.NewGuid();
        Category = category;
        Level = level;
        Title = string.IsNullOrWhiteSpace(title) ? $"{category.GetDisplayName()} - {level.GetLabel()}" : title.Trim();
        Description = description?.Trim() ?? string.Empty;
        StarterCode = starterCode?.Trim() ?? string.Empty;
        ExpectedOutputFormat = string.IsNullOrWhiteSpace(expectedOutputFormat) ? "C# Source File (.cs)" : expectedOutputFormat.Trim();
        Hints = hints?.Trim() ?? string.Empty;
        IsAIGenerated = isAiGenerated;
        PreviousExerciseReferenceId = previousExerciseReferenceId;
        CreatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Factory method to create a valid <see cref="Exercise"/> aggregate instance.
    /// </summary>
    /// <param name="category">The category dimension.</param>
    /// <param name="level">The difficulty tier.</param>
    /// <param name="title">Descriptive title.</param>
    /// <param name="description">Problem statement.</param>
    /// <param name="starterCode">Starter boilerplate.</param>
    /// <param name="expectedOutputFormat">Deliverable format.</param>
    /// <param name="hints">Guidance hints.</param>
    /// <param name="isAiGenerated">Whether generated by LLM.</param>
    /// <param name="previousExerciseReferenceId">Previous exercise ID for diversity.</param>
    /// <returns>A new <see cref="Exercise"/> instance.</returns>
    public static Exercise Create(
        CategoryType category,
        DifficultyLevel level,
        string title,
        string description,
        string starterCode,
        string expectedOutputFormat = "C# Source File (.cs) or Architectural Justification",
        string hints = "",
        bool isAiGenerated = false,
        Guid? previousExerciseReferenceId = null)
    {
        return new Exercise(
            category,
            level,
            title,
            description,
            starterCode,
            expectedOutputFormat,
            hints,
            isAiGenerated,
            previousExerciseReferenceId);
    }

    /// <summary>
    /// Adds a submission to the exercise history while verifying invariant ownership.
    /// </summary>
    /// <param name="submission">The candidate submission.</param>
    /// <exception cref="ArgumentNullException">Thrown when submission is null.</exception>
    /// <exception cref="InvalidOperationException">Thrown when submission does not match this exercise.</exception>
    public void AddSubmission(Submission submission)
    {
        ArgumentNullException.ThrowIfNull(submission);

        if (submission.ExerciseId != Id)
            throw new InvalidOperationException($"Submission exercise ID '{submission.ExerciseId}' does not match exercise ID '{Id}'.");

        _submissions.Add(submission);
    }
}
